### ISSUE TITLE
LEX-1100 and LEX-1101 Code review 

### ISSUE THREAD

**Issue by ynx** [acquia/lift-sdk-php#1]
Thank you @nickveenhof for inviting me into the code review. 

It is extremely swift of you to get the module up and running in merely a couple of days. Kodos to you.

The following recommendations are how I would have approached this project in general, and as to an intermediate-to-long-term goal where the code would rest at. I understand that you may be already aware some of those items (but no time to implement), so please take those as general feedback, and not as immediate change-requests.
1. **Code responsibilities and directory structure.** I would model after Symfony community convention, or reputable projects such as [google-api-php-client](https://github.com/google/google-api-php-client), so I would attempt to organize code as follows:
   - Acquia\LiftClient\Entity\Entity: Abstract Base Entity class. Supports id getter and setters.
   - Acquia\LiftClient\Entity\Slot: Extend from Entity. Dumb data entity, and supports only attribute setters and getters.
   - Acquia\LiftClient\Entity\EntityManager: Abstract EntityManager class. Supports standard Symfony / Doctrine 2 [Entity Manager operations](http://www.doctrine-project.org/api/orm/2.5/class-Doctrine.ORM.EntityManager.html) operations "newInstance, find, findAll, persist, remove". Supports our special needs "serialize, deserialize". Possibly supports some additional functions (findBy, findOneBy, refresh, detach, etc), if deemed useful.
   - Acquia\LiftClient\Entity\SlotManager: Extend from EntityManager. Also encapsulates visibility logic.
   - Acquia\LiftClient\Rest\ApiUrlGenerator: Intakes Entity and operation type, outputs API URL.
   - Acquia\LiftClient\Validator\RestValidator: Intakes Guzzle Request, do validation, error/exception handling.
   - Acquia\LiftClient\Rest\RestService: Supports "get, post, put, delete, ping, etc". 
     - Uses ApiUrlGenerator to get API URL.
     - Uses Guzzle Requests to talk to API.
     - Uses RestValidator to validate the requests.
   - LiftClient: Mothership that employees everybody else.
2. **Tests**. If we break down like above, the unit tests should be able to cover a lot of code.
3. **Dependency.** I could not find the project's target codebases in the Jira tickets. If this project is also expected to be Drupal 7 and/or WordPress -compatible, we may have to consider removing Symfony bundles dependencies.

**Comment by tmeire** [comment]
Nick suggested I take a look at adding some of the code responsibility suggestions, but it feels heavily over engineered for the current state of the sdk. There is only 1 entity type. These suggestions would add a whole bunch of boilerplate that doesn't give us anything extra at the moment. I would revisit some of these suggestions as more entity types are added and there is more code duplication. I'm considering these suggestions as long-term goals for now, as you said.

**Comment by ynx** [comment]
Thank you for the reply @blackskad. For me personally, I start off with most items because:
- I personally rely heavily on unit tests, and those splits help me with managing my tests.
- Clear split of responsibilities helps me OOP well.

I still think "EntityManager conventional method naming" ("newInstance, find, findAll, persist, remove, serialize, deserialize") is useful immediately, due to the fact that they are straight changes, and module is suppose to be consumed externally.

I understand other programmers approach differently, and I agree that most items are no need to be done right now.
