### ISSUE TITLE
Tag an official release

### ISSUE THREAD

**Issue by dpagini** [acquia/lift-sdk-php#26]
Since #25 was closed (totally understand, that turned into a support ticket!) I wanted to update a formal request to tag a release of this SDK.
There was some chat in that issue about a `v1.0` or even `v0.1` or whatever, but it would be great to specify a release in my composer file as opposed to using a commit hash, which is what I'm currently doing.
In addition, once a release is tagged, can this be registered on packagist as well?

**Comment by ynx** [comment]
I'd personally support a `v1.0` and packagist. @tottey please consider and prioritize.

**Comment by ynx** [comment]
@dpagini sorry to close #25 prematurely! I totally forgot the version part of the request. And thank you for opening this #26. ^^

**Comment by dpagini** [comment]
@ynx no worries at all! I think this made a lot of sense b/c this is much more clear ask. Thanks again for your help and pings to help move this request along!

**Comment by ynx** [comment]
Tagged `0.9.0`. I didn't go for `1.0.0` yet because I feel this library is not feature "complete" yet. I will attempt to release to packagist once I get Acquia's packagist maintainer access.

**Comment by dpagini** [comment]
Awesome, thank you @ynx!

I actually see it out there right now: https://packagist.org/packages/acquia/lift-sdk-php

I'm going to close this issue, but please reopen it if you think it needs to stay open to track anything else.

**Comment by ynx** [comment]
@dpagini Oh yes one of engineers helped me publish on Packagist and I was in process of confirming with him - good that you just confirmed with me. Yes, closed.

Thank you very much for the input! Please let me know if anything else.
