### ISSUE TITLE
Do new slots need to have their HTML (Embed code) explicitly set?

### ISSUE THREAD

**Issue by mortenson** [acquia/lift-sdk-php#3]
I noticed that new slots created with this SDK do not contain an "Embed code" when viewing them via the Lift UI. Do I need to explicitly set the HTML of new Slots to get this to show up?

AKA, do I need to do this when creating a slot `$slot->setHtml('<div data-lift-slot="' . $some_id . '"></div>');` ?

**Comment by nickveenhof** [comment]
You can just ask for getHtml and it should give you the code.

**Comment by mortenson** [comment]
For new slots I create with the SDK, there is no HTML by default. So when you configure the Slot in the Lift UI, the "Embed Code" field is empty.

**Comment by nickveenhof** [comment]
Removed the html function as the html can be freely decided by the implementer. When using Lift 3 it needs to use the conventions, but the API doesn't care for making decisions.

**Comment by mortenson** [comment]
I think my question is still unanswered, the replication steps for the behavior I'm seeing are:
1. Create a slot per the documentation at https://github.com/acquia/lift-sdk-php/blob/master/README.md#usage
2. Open the Lift sidebar
3. Configure the slot in the sidebar
4. See that the "Embed Code" field is empty

How do I create a Slot so that the "Embed Code" field is not initially empty?

**Comment by nickveenhof** [comment]
Created an internal Acquia ticket to address this issue as it is not an SDK issue. Not exposing the identifier given that this is a public repository
