### ISSUE TITLE
does not work with Lift v4

### ISSUE THREAD

**Issue by jasonlttl** [acquia/lift-sdk-php#31]
In Lift v4, there were significant changes that introduced campaigns as well as changes to the way rules were modeled and content associated. 

This SDK is hard coded to use old routes for things like rules.
* http://docs.lift.acquia.com/decision/#rules_get

And the routes used by Lift V4 have fairly different return structures.
* http://docs.lift.acquia.com/decision/v2/#rules_get

**Comment by baophan1** [comment]
Just released the Lift v4 SDK to the public so feel free to start using it. Do keep in mind that the default branch will still be Lift3 (aka. master) branch so do pull from Lift4 branch. Eventually we will set Lift4 as the default branch and we will send out a notification with adequate time for our clients to transition over

https://github.com/acquia/lift-sdk-php/tree/Lift4
